sudo: required
language: rust
os:
 - linux
 - osx
rust:
 - stable
 - beta
 - nightly
matrix:
 allow_failures:
  - rust: nightly
script:
- cargo build --release
- make test
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
after_success: make codecov
