language: rust
os:
 - linux
 - osx
rust:
 - stable
 - beta
 - nightly
matrix:
 allow_failures:
  - rust: nightly
script:
- cargo build --release
- for example in examples/*; do echo $example && cp $example src/main.rs && cargo run; done
