[package]
name = "polish"
description = "Polish is a mini testing framework for the Rust system programming language meant to allow the writing of test-driven applications in a unified and expressive manner."
version = "0.1.0"
authors = ["Fadi Hanna Al-Kass"]

[[test]]
name = "test_runner"

[dependencies]
chrono = "0.3.0"
ansi_term = "0.9.0"
time = "0.1.37"
