name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: clippy, rustfmt

    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.toolchain }}-cargo-registry-

    - uses: actions/cache@v3
      with:
        path: ~/.cargo/index
        key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.toolchain }}-cargo-index-

    - uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.toolchain }}-cargo-build-

    - name: Build
      run: cargo build --release --verbose

    - name: Run example tests
      run: make test

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run Rustfmt
      run: cargo fmt -- --check
